<?php

namespace Sitephys\PhysmvcBundle\Repository\Entity;

/**
 * PhysaddtopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhysaddtopicRepository extends \Doctrine\ORM\EntityRepository
{
}
