sitephys_physmvc:
    resource: "@SitephysPhysmvcBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults:
        _controller: SitephysUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout

logtarget:
    path: /
    defaults:
        _controller: SitephysPhysmvcBundle:Phys:home