# app/config/security.yml

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Sitephys\UserBundle\Entity\User: plaintext
        # Sitephys\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_AUTHOR, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user: { password: userpass, roles: [ 'ROLE_USER' ] }
                    author: { password: authorpass, roles: [ 'ROLE_AUTHOR' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
                    superadmin: { password: superadminpass, roles: [ 'ROLE_SUPER_ADMIN' ] }
        main:
            entity:
                class:    Sitephys\UserBundle\Entity\User
                property: username

    firewalls:
        main:
            pattern:      ^/
            anonymous:    true
            provider:     main
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: /
            logout:
                path:       logout
                target:     /

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
