# app/config/security.yml

security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    user: { password: userpass, roles: [ 'ROLE_USER' ] }
                    author: { password: authorpass, roles: [ 'ROLE_AUTHOR' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
                    superadmin: { password: superadminpass, roles: [ 'ROLE_SUPER_ADMIN' ] }
        auth_token_user_provider:
            id: auth_token_user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            stateless: true
            simple_preauth:
                authenticator: auth_token_authenticator
            provider: auth_token_user_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: /
            logout:
                path:       logout
                target:     /
            remember_me:
                secret:     %secret%

    encoders:
        Sitephys\UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
