# app/config/security.yml

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Sitephys\UserBundle\Entity\User: sha512
        # Sitephys\UserBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_AUTHOR, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user: { roles: [ 'ROLE_USER' ] }
                    author: { roles: [ 'ROLE_AUTHOR' ] }
                    admin: { roles: [ 'ROLE_ADMIN' ] }
                    superadmin: { roles: [ 'ROLE_SUPER_ADMIN' ] }

        main:
            entity:
                class:    Sitephys\UserBundle\Entity\User
                property: username

    firewalls:
        main:
            pattern: ^/
            anonymous:    true
            provider:     main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:       logout
                target:     /
            #remember_me:
            #    secret:     %secret%

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
