<?php

namespace Sitephys\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByApikey($apiKey)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT u.username, u.roles FROM SitephysUserBundle:User u WHERE u.apikey = ' . $apiKey
            )
            ->getResult();
    }
}
