sitephys_physmvc_home:
    path:      /
    defaults:
        _controller: SitephysPhysmvcBundle:Phys:home

sitephys_physmvc_topic:
    path:      /topic/
    defaults:
        _controller: SitephysPhysmvcBundle:Phys:top

sitephys_physmvc_symbolization:
    path:      /symbolization/
    defaults:
        _controller: SitephysPhysmvcBundle:Phys:sym

sitephys_physmvc_evaluation:
    path:      /evaluation/{idTopic}
    defaults:
        _controller: SitephysPhysmvcBundle:Phys:eval

sitephys_physmvc_phys_view:
    path:      /phys/{id}
    defaults:
        _controller: SitephysPhysmvcBundle:Phys:view

sitephys_physmvc_phys_hometopic:
    path:      /hometopics/{idTopic}
    defaults:
        _controller: SitephysPhysmvcBundle:Phys:hometopic

sitephys_physmvc_phys_global:
    path:      /topics/{idTopic}/{intLevel}
    defaults:
        _controller: SitephysPhysmvcBundle:Phys:global

sitephys_physmvc_phys_element:
    path:      /topics/{idTopic}/{intLevel}/{intEltLevel}
    defaults:
        _controller: SitephysPhysmvcBundle:Phys:element

sitephys_physmvc_edition:
    path:      /edition/
    defaults:
        _controller: SitephysPhysmvcBundle:Phys:homeedit

sitephys_physmvc_edition_add:
    path:      /edition/add/{idthing}
    defaults:
        _controller: SitephysPhysmvcBundle:Phys:add

sitephys_physmvc_edition_update:
    path:      /edition/update/{id}
    defaults:
        _controller: SitephysPhysmvcBundle:Phys:update
    requirements:
        id: \d+
