sitephys_physmvc_home:
    path:      /
    defaults:
        _controller: SitephysPhysmvcBundle:Phys:home

sitephys_physmvc_presentation:
    path:      /presentation/
    defaults:
        _controller: SitephysPhysmvcBundle:Phys:presentation

sitephys_physmvc_topic:
    path:      /topic/
    defaults:
        _controller: SitephysPhysmvcBundle:Phys:top

sitephys_physmvc_symbolization:
    path:      /symbolization/
    defaults:
        _controller: SitephysPhysmvcBundle:Phys:sym

sitephys_physmvc_evaluation:
    path:      /evaluation/{idTopic}
    defaults:
        _controller: SitephysPhysmvcBundle:Phys:eval

sitephys_physmvc_phys_view:
    path:      /phys/{id}
    defaults:
        _controller: SitephysPhysmvcBundle:Phys:view

sitephys_physmvc_phys_hometopic:
    path:      /hometopics/{idTopic}
    defaults:
        _controller: SitephysPhysmvcBundle:Phys:hometopic

sitephys_physmvc_phys_global:
    path:      /topics/{idTopic}/{intLevel}
    defaults:
        _controller: SitephysPhysmvcBundle:Phys:global

sitephys_physmvc_phys_element:
    path:      /topics/{idTopic}/{intLevel}/{intEltLevel}
    defaults:
        _controller: SitephysPhysmvcBundle:Phys:element

sitephys_physmvc_edition:
    path:      /edition/
    defaults:
        _controller: SitephysPhysmvcBundle:Edit:homeedit

sitephys_physmvc_edition_add:
    path:      /edition/add/
    defaults:
        _controller: SitephysPhysmvcBundle:Edit:add

sitephys_physmvc_edition_addtopic:
    path:      /edition/addtopic/{iddom}
    defaults:
        _controller: SitephysPhysmvcBundle:Edit:addtopic

sitephys_physmvc_edition_update:
    path:      /edition/update/{id}
    defaults:
        _controller: SitephysPhysmvcBundle:Edit:update
    requirements:
        id: \d+

sitephys_physmvc_edition_viewadd:
    path:      /edition/viewadd/{idadd}
    defaults:
        _controller: SitephysPhysmvcBundle:Edit:viewadd

sitephys_physmvc_edition_viewaddtopic:
    path:      /edition/viewaddtopic/{idaddtopic}
    defaults:
        _controller: SitephysPhysmvcBundle:Edit:viewaddtopic

sitephys_physmvc_edition_viewupd:
    path:      /edition/viewupd/{idphys}
    defaults:
        _controller: SitephysPhysmvcBundle:Edit:viewupd

sitephys_user_login:
    path:      /login
    defaults:
        _controller: SitephysUserBundle:Security:login

sitephys_user_account:
    path:      /user
    defaults:
        _controller: SitephysUserBundle:Security:homeuser

sitephys_user_add:
    path:      /user/add/{roleuser}
    defaults:
        _controller: SitephysUserBundle:Security:adduser

sitephys_user_delete:
    path:      /user/delete/{iduser}
    defaults:
        _controller: SitephysUserBundle:Security:deleteuser

sitephys_user_email:
    path:      /user/email/{name}
    defaults:
        _controller: SitephysUserBundle:Security:emailuser