<?php

namespace Proxies\__CG__\Sitephys\PhysmvcBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Physaddtopic extends \Sitephys\PhysmvcBundle\Entity\Physaddtopic implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'id', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'domainid', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'mode', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'title', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'username', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'email', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'date', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'contentexpin', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'contentth', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'contentexpout', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'contentretexpin', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'contentretth', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'contentretexpout', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'weblink'];
        }

        return ['__isInitialized__', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'id', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'domainid', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'mode', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'title', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'username', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'email', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'date', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'contentexpin', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'contentth', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'contentexpout', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'contentretexpin', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'contentretth', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'contentretexpout', '' . "\0" . 'Sitephys\\PhysmvcBundle\\Entity\\Physaddtopic' . "\0" . 'weblink'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Physaddtopic $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomainid($domainid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomainid', [$domainid]);

        return parent::setDomainid($domainid);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomainid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomainid', []);

        return parent::getDomainid();
    }

    /**
     * {@inheritDoc}
     */
    public function setMode($mode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMode', [$mode]);

        return parent::setMode($mode);
    }

    /**
     * {@inheritDoc}
     */
    public function getMode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMode', []);

        return parent::getMode();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$username]);

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setContentexpin($contentexpin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentexpin', [$contentexpin]);

        return parent::setContentexpin($contentexpin);
    }

    /**
     * {@inheritDoc}
     */
    public function getContentexpin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentexpin', []);

        return parent::getContentexpin();
    }

    /**
     * {@inheritDoc}
     */
    public function setContentth($contentth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentth', [$contentth]);

        return parent::setContentth($contentth);
    }

    /**
     * {@inheritDoc}
     */
    public function getContentth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentth', []);

        return parent::getContentth();
    }

    /**
     * {@inheritDoc}
     */
    public function setContentexpout($contentexpout)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentexpout', [$contentexpout]);

        return parent::setContentexpout($contentexpout);
    }

    /**
     * {@inheritDoc}
     */
    public function getContentexpout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentexpout', []);

        return parent::getContentexpout();
    }

    /**
     * {@inheritDoc}
     */
    public function setContentretexpin($contentretexpin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentretexpin', [$contentretexpin]);

        return parent::setContentretexpin($contentretexpin);
    }

    /**
     * {@inheritDoc}
     */
    public function getContentretexpin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentretexpin', []);

        return parent::getContentretexpin();
    }

    /**
     * {@inheritDoc}
     */
    public function setContentretth($contentretth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentretth', [$contentretth]);

        return parent::setContentretth($contentretth);
    }

    /**
     * {@inheritDoc}
     */
    public function getContentretth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentretth', []);

        return parent::getContentretth();
    }

    /**
     * {@inheritDoc}
     */
    public function setContentretexpout($contentretexpout)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentretexpout', [$contentretexpout]);

        return parent::setContentretexpout($contentretexpout);
    }

    /**
     * {@inheritDoc}
     */
    public function getContentretexpout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentretexpout', []);

        return parent::getContentretexpout();
    }

    /**
     * {@inheritDoc}
     */
    public function setWeblink($weblink)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeblink', [$weblink]);

        return parent::setWeblink($weblink);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeblink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeblink', []);

        return parent::getWeblink();
    }

}
